### ISSUE TITLE
data/labels.json should use named keys for dataset slots

### ISSUE THREAD

**Issue by AbeHandler** [fortytw0/needfinder#10]
from `src.main`
<img width="479" alt="Screen Shot 2022-06-29 at 1 04 19 PM" src="https://user-images.githubusercontent.com/1252925/176515963-73f597f1-9744-45ec-9717-4bec28dcd4bb.png">

Using numbered slots for each dataset will get really confusing. We should refactor.

**Comment by fortytw0** [comment]
I agree - ideally this should change, but at the moment since we are only focussing on these subreddits, I am lettting it slide. In the future, I envision a command line prompt that will accept a JSON file path. Don't know if this is satisfactory- but please let me know if it won't work for your purposes

**Comment by AbeHandler** [comment]
works for me for now!
